### ISSUE TITLE
Environment variables types

### ISSUE THREAD

**Issue by vincent-tr** [billchurch/read-config-ng#13]
Hi,

I'm glad to see that someone is taking over on `read-config`!

I'm trying to achieve environment variable overrides on other types than string, eg:

```json
{
  "number1": "%{NUMBER1|42}",
  "boolean1": "%{BOOLEAN1|false}"
}
```

It work fine when using the default values, but I cannot get the right types when using environment variables overrides, eg:

```bash
NUMBER1=43 BOOLEAN1=true node -p "require('read-config')('./test.json')"
{ number1: '43', boolean1: 'true' }
```

I would like to expect: 
```bash
{ number1: 43, boolean1: true }
```
(with no quote)

Is there some way to achieve this?

**Comment by billchurch** [comment]
Shell variables have no type, so they're interpreted as string. 

You'll need to force those variables to be a boolean, integer, or whatever with a function of some sort...

Hard for me to do as a one-liner but something like this (bare bones, probably want more checking and error handling here):

index.js:

```javascript
const config = require('read-config-ng')('./test.json')

config.boolean1 = (config.boolean1 == "true")
config.number1 = (parseInt(config.number1))

console.log(JSON.stringify(config))
```

test:
```bash
BOOLEAN1=true NUMBER1=99 node index.js 
{"number1":99,"boolean1":true}
```

```bash
BOOLEAN1=true NUMBER1=99 node index.js 
node index.js 
{"number1":42,"boolean1":false}
```

**Comment by billchurch** [comment]
also, don't forget to call the right module "read-config-**ng**"

**Comment by vincent-tr** [comment]
I see the idea.

Thanks!
